### PR TITLE
Centering the map

### PR DESCRIPTION
**Pull request by matq007**
Added centering based on all markers on the map. If the distance is greater than 6.0 ignore centering.

### CODE REVIEW

**Comment by marklonquist** [comment]
Can you add the possibility of disabling this in the backend? :-)

**Comment by matq007** [comment]
Yes, can I use center on marker and just rename it to center on markers?

**Comment by marklonquist** [comment]
Yes, it makes sense. :-)

**Comment by matq007** [comment]
Done. Can you check it out?

**Comment by marklonquist** [comment]
Almost there! You forgot to remove your console.log. :-)

**Comment by matq007** [comment]
Removed console.log

**Pull request merged**
